# makefile
# PARA INIT
CXX = g++
SRC_DIR = ./randomWalk

# Name of the target executable program
MAIN_TARGET = example

OBJS = main.o randomWalk.o 
# using C++14 standard
STD = -std=c++14 
CFLAG = -Wall -I $(SRC_DIR)