# PARA INIT
CXX = c++
SRC_DIR1 = ./testPrint
# Name of the target executable program
MAIN_TARGET = example

OBJS = main.o testPrint.o
# using C++14 standard
STD = -std=c++14 
CFLAG = -Wall -I $(SRC_DIR1) 