# This CLASS is Usually used as a package

include ../makefile.config

formatOutput.o : formatOutput.h
	$(CXX) $(STD) -Wall -c formatOutput.cpp -o ../formatOutput.o

.PHONY : clean
clean :
	rm -rf ../formatOutput.o