# makefile
# PARA INIT
CXX = g++
SRC_DIR1 = ./testPrint
SRC_DIR2 = ./formatOutput
SRC_DIR3 = ../SQLAPI
# Name of the target executable program
MAIN_TARGET = example

OBJS = main.o testPrint.o formatOutput.o
# using C++14 standard
# 
STD = -std=c++14 
CFLAG = -Wall -I $(SRC_DIR1) -I $(SRC_DIR2) -I $(SRC_DIR3)/include -L$(SRC_DIR3)/lib -llibsqlapiu
