# makefile
# PARA INIT
CXX = g++

# package name
PKG = MCWalk

SRC_DIR = ./$(PKG)



# Name of the target executable program
MAIN_TARGET = example

OBJS = main.o MCWalk.o 

# using C++11 standard
STD = -std=c++11 
CFLAG = -Wall -Wextra
INC = -I $(SRC_DIR)