# This CLASS is Usually used as a package
include ../makefile.config

randomWalk.o : randomWalk.h
	$(CXX) $(STD) -Wall -c randomWalk.cpp -o ../randomWalk.o

.PHONY : clean
clean :
	rm -rf ../randomWalk.o